### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by hexley21** [hexley21/DataLens-SaaS#1]
# To-Do

Register/Login (company/employee)

- [x] register
- [x] authentication [email - nodemailerl]
- [x] authorization (JWT)

Tiers

- [x] free: 10 files, 1 user, (price 0$)
- [x] basic 100 files 10 users +5$ per user, (price 0$)
- [x] premium 1000 files, ∞ users,  0.5$ per additional file (price 300$)

Employees

- [x] add/remove
- [x] authentication (add password) [email]
- [x] authorization (JWT)

Employee Abilities

- [x] upload only (csv, xls, xlsx)
- [x] control file visibility options (on/off/selected) [changeable] 
- [x] change password

Company Abilities

- [x] see everything
- [x] see the current plan
- [x] change personal info
- [x] downgrade & upgrade plans
- [x] See employee list
- [x] Ability to pay the bill
- [x] Access restriction on unpaid bills

General
- [x] write tests
- [x] document
